### ISSUE TITLE
很抱歉以这种方式联系您

### ISSUE THREAD

**Issue by kahosan** [ShiinaNene/HealthModule-DamageList#1]
不知您以前做的爱恋的同人游戏是否还在呢?
推完游戏之后一阵空虚难受 无意中在贴吧里看见有做同人游戏的大佬
但获取方式都已失效 只好寻找原作者来问问
如果您愿意再分享一次 万分感激

**Comment by ShiinaNene** [comment]
黑历史啊 那个剧情我越看越尬 见笑了 
百度盘 1HnOuI_XFpW5MzJPZXjhRsg     tfxg

**Comment by ShiinaNene** [comment]
解压密码好像是 25565 来着

**Comment by kahosan** [comment]
> 解压密码好像是 25565 来着

非常感谢
